name: YouTube Video Checker

on:

#  schedule:
#     - cron: '10 0 21-29 * *'
#     - cron: '45 12 21-29 * *'
     

  workflow_dispatch: {}

jobs:
  check_videos:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16  # 或您想要使用的更高版本
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install requests google-api-python-client discord.py

    - name: Run script
      env:
        YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        DISCORD_WEBHOOK_TEST: ${{ secrets. DISCORD_WEBHOOK_TEST }}
        DISCORD_WEBHOOK_URL_2: ${{ secrets. DISCORD_WEBHOOK_URL_2 }}
        DISCORD_WEBHOOK_BC4: ${{ secrets. DISCORD_WEBHOOK_BC4 }}
      run: |
        python main.py
